//! onesync repo-housekeeping tasks.

#![forbid(unsafe_code)]
#![allow(clippy::unwrap_used, clippy::expect_used)]
// LINT: this is a developer-tooling binary, not production code.

use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use rusqlite::Connection;

#[derive(Parser)]
struct Cli {
    #[command(subcommand)]
    command: Cmd,
}

#[derive(Subcommand)]
enum Cmd {
    /// Write the current schema (as produced by the embedded migrations) to schema.sql.
    DumpSchema {
        /// Output path; defaults to crates/onesync-state/schema.sql.
        #[arg(long)]
        out: Option<PathBuf>,
    },
    /// Verify that crates/onesync-state/schema.sql matches the embedded migrations.
    CheckSchema {
        /// Path to schema.sql; defaults to crates/onesync-state/schema.sql.
        #[arg(long)]
        path: Option<PathBuf>,
    },
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    match cli.command {
        Cmd::DumpSchema { out } => {
            let path = out.unwrap_or_else(default_schema_path);
            let dump = dump()?;
            std::fs::write(&path, &dump).with_context(|| format!("write {}", path.display()))?;
            println!("wrote {}", path.display());
        }
        Cmd::CheckSchema { path } => {
            let path = path.unwrap_or_else(default_schema_path);
            let on_disk = std::fs::read_to_string(&path)
                .with_context(|| format!("read {}", path.display()))?;
            let from_migrations = dump()?;
            if on_disk.trim() != from_migrations.trim() {
                eprintln!(
                    "{} diverges from embedded migrations. \
                     Run `cargo run -p xtask -- dump-schema` to refresh.",
                    path.display()
                );
                std::process::exit(1);
            }
            println!("ok ({})", path.display());
        }
    }
    Ok(())
}

fn default_schema_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("workspace root")
        .join("crates/onesync-state/schema.sql")
}

fn dump() -> Result<String> {
    let mut conn = Connection::open_in_memory().context("open memory db")?;
    onesync_state::migrations::run(&mut conn).map_err(|e| anyhow::anyhow!("migrations: {e}"))?;

    // Iterate sqlite_schema rows (ignore the auto-generated indexes and the refinery table).
    let mut stmt = conn
        .prepare(
            "SELECT sql FROM sqlite_schema
         WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' AND name NOT LIKE 'refinery_%'
         ORDER BY name",
        )
        .context("prepare")?;
    let mut out = String::from(
        "-- Auto-generated by `cargo run -p xtask -- dump-schema`. Do not edit by hand.\n\n",
    );
    for row in stmt
        .query_map([], |r| r.get::<_, String>(0))
        .context("query")?
    {
        let sql = row.context("row")?;
        out.push_str(&sql);
        out.push_str(";\n\n");
    }
    Ok(out)
}
