-- Auto-generated by `cargo run -p xtask -- dump-schema`. Do not edit by hand.

CREATE TABLE accounts (
    id              TEXT PRIMARY KEY,
    kind            TEXT NOT NULL CHECK (kind IN ('personal','business')),
    upn             TEXT NOT NULL,
    tenant_id       TEXT NOT NULL,
    drive_id        TEXT NOT NULL,
    display_name    TEXT NOT NULL,
    keychain_ref    TEXT NOT NULL,
    scopes_json     TEXT NOT NULL,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL
);

CREATE UNIQUE INDEX accounts_upn_uq ON accounts(upn);

CREATE TABLE audit_events (
    id            TEXT PRIMARY KEY,
    ts            TEXT NOT NULL,
    level         TEXT NOT NULL CHECK (level IN ('info','warn','error')),
    kind          TEXT NOT NULL,
    pair_id       TEXT REFERENCES pairs(id) ON DELETE SET NULL,
    payload_json  TEXT NOT NULL
);

CREATE INDEX audit_events_ts_idx ON audit_events(ts DESC);

CREATE TABLE conflicts (
    id                     TEXT PRIMARY KEY,
    pair_id                TEXT NOT NULL REFERENCES pairs(id) ON DELETE CASCADE,
    relative_path          TEXT NOT NULL,
    winner                 TEXT NOT NULL CHECK (winner IN ('local','remote')),
    loser_relative_path    TEXT NOT NULL,
    local_side_json        TEXT NOT NULL,
    remote_side_json       TEXT NOT NULL,
    detected_at            TEXT NOT NULL,
    resolved_at            TEXT,
    resolution             TEXT,
    note                   TEXT
);

CREATE INDEX conflicts_pair_unresolved_idx
    ON conflicts(pair_id)
    WHERE resolved_at IS NULL;

CREATE TABLE file_entries (
    pair_id            TEXT NOT NULL REFERENCES pairs(id) ON DELETE CASCADE,
    relative_path      TEXT NOT NULL,
    kind               TEXT NOT NULL CHECK (kind IN ('file','directory')),
    sync_state         TEXT NOT NULL CHECK
                          (sync_state IN ('clean','dirty','pending_upload',
                                          'pending_download','pending_conflict','in_flight')),
    local_json         TEXT,
    remote_json        TEXT,
    synced_json        TEXT,
    pending_op_id      TEXT REFERENCES file_ops(id) ON DELETE SET NULL,
    updated_at         TEXT NOT NULL,
    PRIMARY KEY (pair_id, relative_path)
);

CREATE INDEX file_entries_dirty_idx
    ON file_entries(pair_id, sync_state)
    WHERE sync_state <> 'clean';

CREATE TABLE file_ops (
    id                 TEXT PRIMARY KEY,
    run_id             TEXT NOT NULL REFERENCES sync_runs(id) ON DELETE CASCADE,
    pair_id            TEXT NOT NULL REFERENCES pairs(id) ON DELETE CASCADE,
    relative_path      TEXT NOT NULL,
    kind               TEXT NOT NULL,
    status             TEXT NOT NULL,
    attempts           INTEGER NOT NULL DEFAULT 0,
    last_error_json    TEXT,
    metadata_json      TEXT,
    enqueued_at        TEXT NOT NULL,
    started_at         TEXT,
    finished_at        TEXT
);

CREATE INDEX file_ops_pair_status_idx ON file_ops(pair_id, status);

CREATE INDEX file_ops_run_idx ON file_ops(run_id);

CREATE TABLE instance_config (
    id            INTEGER PRIMARY KEY CHECK (id = 1),
    log_level     TEXT NOT NULL DEFAULT 'info',
    notify        INTEGER NOT NULL DEFAULT 1,
    allow_metered INTEGER NOT NULL DEFAULT 0,
    min_free_gib  INTEGER NOT NULL DEFAULT 2,
    updated_at    TEXT NOT NULL
, azure_ad_client_id TEXT NOT NULL DEFAULT '', webhook_listener_port INTEGER, webhook_notification_url TEXT);

CREATE TABLE pairs (
    id                 TEXT PRIMARY KEY,
    account_id         TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    local_path         TEXT NOT NULL,
    remote_item_id     TEXT NOT NULL,
    remote_path        TEXT NOT NULL,
    display_name       TEXT NOT NULL,
    status             TEXT NOT NULL CHECK
                          (status IN ('initializing','active','paused','errored','removed')),
    paused             INTEGER NOT NULL DEFAULT 0,
    delta_token        TEXT,
    errored_reason     TEXT,
    created_at         TEXT NOT NULL,
    updated_at         TEXT NOT NULL,
    last_sync_at       TEXT,
    conflict_count     INTEGER NOT NULL DEFAULT 0
, webhook_enabled INTEGER NOT NULL DEFAULT 0);

CREATE INDEX pairs_account_idx ON pairs(account_id);

CREATE UNIQUE INDEX pairs_local_path_uq ON pairs(local_path) WHERE status <> 'removed';

CREATE UNIQUE INDEX pairs_remote_uq
    ON pairs(account_id, remote_item_id) WHERE status <> 'removed';

CREATE TABLE sync_runs (
    id                 TEXT PRIMARY KEY,
    pair_id            TEXT NOT NULL REFERENCES pairs(id) ON DELETE CASCADE,
    trigger            TEXT NOT NULL,
    started_at         TEXT NOT NULL,
    finished_at        TEXT,
    local_ops          INTEGER NOT NULL DEFAULT 0,
    remote_ops         INTEGER NOT NULL DEFAULT 0,
    bytes_uploaded     INTEGER NOT NULL DEFAULT 0,
    bytes_downloaded   INTEGER NOT NULL DEFAULT 0,
    outcome            TEXT,
    outcome_detail     TEXT
);

CREATE INDEX sync_runs_pair_started_idx ON sync_runs(pair_id, started_at DESC);

